<?= $this->extend('layouts/main') ?>

<?= $this->section('title') ?>Report Details<?= $this->endSection() ?>

<?= $this->section('styles') ?>
<style>
.status-badge { 
    display: inline-block;
    padding: 0.25rem 0.75rem;
    border-radius: 9999px;
    font-weight: 600;
    font-size: 0.875rem;
}
</style>
<?= $this->endSection() ?>

<?= $this->section('content') ?>

<div class="space-y-6">
    <!-- Page Header -->
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
            <h1 class="text-2xl font-bold text-gray-900"><i class="fas fa-file-alt mr-2"></i>Safety Report Details</h1>
            <p class="text-gray-600 text-sm mt-1"><?= $report['report_code'] ?? 'Report' ?></p>
        </div>
        <a href="<?= base_url('incident-safety/reports') ?>" class="inline-flex items-center px-4 py-2 bg-gray-600 text-white rounded-lg hover:bg-gray-700 transition-colors">
            <i class="fas fa-arrow-left mr-2"></i> Back
        </a>
    </div>

    <!-- Alerts -->
    <?php if (session()->getFlashdata('success')): ?>
        <div class="bg-green-50 border border-green-200 text-green-800 px-4 py-3 rounded-lg flex justify-between items-center">
            <span><?= session()->getFlashdata('success') ?></span>
            <button type="button" class="text-green-800 hover:text-green-900 text-xl">&times;</button>
        </div>
    <?php endif; ?>

    <!-- Report Information -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div class="lg:col-span-2">
            <div class="bg-white rounded-lg shadow-sm border p-6">
                <h2 class="text-xl font-bold text-gray-900 mb-6">Report Information</h2>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Report Code</label>
                        <p class="text-lg font-semibold text-gray-900"><?= $report['report_code'] ?? 'N/A' ?></p>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Report Type</label>
                        <p>
                            <?php 
                            $reportTypeColors = [
                                'daily' => 'bg-blue-100 text-blue-800',
                                'weekly' => 'bg-green-100 text-green-800',
                                'monthly' => 'bg-purple-100 text-purple-800',
                                'quarterly' => 'bg-indigo-100 text-indigo-800',
                                'annual' => 'bg-red-100 text-red-800'
                            ];
                            $typeClass = $reportTypeColors[$report['report_type'] ?? ''] ?? 'bg-gray-100 text-gray-800';
                            ?>
                            <span class="<?= $typeClass ?> px-3 py-1 rounded-full text-sm font-medium">
                                <?= ucfirst($report['report_type'] ?? '') ?>
                            </span>
                        </p>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Project</label>
                        <p class="text-lg font-semibold text-gray-900"><?= $report['project_name'] ?? 'N/A' ?></p>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Report Period</label>
                        <p class="text-lg font-semibold text-gray-900">
                            <?= date('M d, Y', strtotime($report['report_period_start'])) ?> - 
                            <?= date('M d, Y', strtotime($report['report_period_end'])) ?>
                        </p>
                    </div>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Generated By</label>
                        <p class="text-lg font-semibold text-gray-900"><?= $report['generated_by_name'] ?? 'N/A' ?></p>
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-1">Status</label>
                        <p>
                            <?php 
                            $statusColors = [
                                'draft' => 'bg-gray-100 text-gray-800',
                                'pending_review' => 'bg-yellow-100 text-yellow-800',
                                'approved' => 'bg-green-100 text-green-800',
                                'published' => 'bg-blue-100 text-blue-800'
                            ];
                            $statusClass = $statusColors[$report['status'] ?? ''] ?? 'bg-gray-100 text-gray-800';
                            ?>
                            <span class="<?= $statusClass ?> px-3 py-1 rounded-full text-sm font-medium">
                                <?= ucfirst(str_replace('_', ' ', $report['status'] ?? '')) ?>
                            </span>
                        </p>
                    </div>
                </div>
            </div>

            <!-- Key Highlights -->
            <?php if (!empty($report['key_highlights'])): ?>
                <div class="bg-white rounded-lg shadow-sm border p-6 mt-6">
                    <h3 class="text-lg font-bold text-gray-900 mb-4 pb-4 border-b">
                        <i class="fas fa-star mr-2"></i>Key Highlights
                    </h3>
                    <p class="text-gray-700 whitespace-pre-wrap"><?= nl2br($report['key_highlights']) ?></p>
                </div>
            <?php endif; ?>

            <!-- Challenges -->
            <?php if (!empty($report['challenges_identified'])): ?>
                <div class="bg-white rounded-lg shadow-sm border p-6 mt-6">
                    <h3 class="text-lg font-bold text-gray-900 mb-4 pb-4 border-b">
                        <i class="fas fa-exclamation-triangle mr-2"></i>Challenges Identified
                    </h3>
                    <p class="text-gray-700 whitespace-pre-wrap"><?= nl2br($report['challenges_identified']) ?></p>
                </div>
            <?php endif; ?>

            <!-- Recommendations -->
            <?php if (!empty($report['recommendations'])): ?>
                <div class="bg-white rounded-lg shadow-sm border p-6 mt-6">
                    <h3 class="text-lg font-bold text-gray-900 mb-4 pb-4 border-b">
                        <i class="fas fa-lightbulb mr-2"></i>Recommendations
                    </h3>
                    <p class="text-gray-700 whitespace-pre-wrap"><?= nl2br($report['recommendations']) ?></p>
                </div>
            <?php endif; ?>

            <!-- Attachments -->
            <div class="bg-white rounded-lg shadow-sm border p-6 mt-6">
                <h3 class="text-lg font-bold text-gray-900 mb-4 pb-4 border-b">
                    <i class="fas fa-file-pdf mr-2"></i>Attached Report
                </h3>
                <?php if (!empty($report['report_file_path'])): ?>
                    <a href="<?= base_url('incident-safety/reports/' . $report['id'] . '/document') ?>" class="inline-flex items-center px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors" download>
                        <i class="fas fa-download mr-2"></i> Download Report
                    </a>
                    <p class="text-xs text-gray-500 mt-2">
                        <i class="fas fa-file mr-1"></i><?= basename($report['report_file_path']) ?>
                    </p>
                <?php else: ?>
                    <p class="text-gray-600 text-sm">
                        <i class="fas fa-info-circle mr-2"></i>No document uploaded for this report.
                    </p>
                <?php endif; ?>
            </div>


            <!-- Approval Information -->
            <?php if ($report['status'] === 'approved' || $report['status'] === 'published'): ?>
                <div class="bg-white rounded-lg shadow-sm border p-6 mt-6">
                    <h3 class="text-lg font-bold text-gray-900 mb-4 pb-4 border-b">
                        <i class="fas fa-check-circle mr-2"></i>Approval Information
                    </h3>
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label class="block text-sm font-medium text-gray-700 mb-1">Approved By</label>
                            <p class="text-lg font-semibold text-gray-900"><?= $report['approved_by_name'] ?? 'N/A' ?></p>
                        </div>
                        <div>
                            <label class="block text-sm font-medium text-gray-700 mb-1">Approval Date</label>
                            <p class="text-lg font-semibold text-gray-900">
                                <?= !empty($report['approved_date']) ? date('M d, Y H:i', strtotime($report['approved_date'])) : 'N/A' ?>
                            </p>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </div>

        <!-- Statistics Card Sidebar -->
        <div>
            <div class="bg-white rounded-lg shadow-sm border p-6">
                <h3 class="text-lg font-bold text-gray-900 mb-6">Safety Statistics</h3>
                
                <div class="space-y-4">
                    <div class="border-l-4 border-gray-500 pl-4">
                        <p class="text-sm text-gray-600">Total Incidents</p>
                        <p class="text-3xl font-bold text-gray-900"><?= $report['total_incidents_reported'] ?? 0 ?></p>
                    </div>

                    <div class="border-l-4 border-orange-500 pl-4">
                        <p class="text-sm text-gray-600">Near Misses</p>
                        <p class="text-3xl font-bold text-orange-600"><?= $report['total_near_misses'] ?? 0 ?></p>
                    </div>

                    <div class="border-l-4 border-red-500 pl-4">
                        <p class="text-sm text-gray-600">Injured Workers</p>
                        <p class="text-3xl font-bold text-red-600"><?= $report['total_injured_workers'] ?? 0 ?></p>
                    </div>

                    <div class="border-l-4 border-blue-500 pl-4">
                        <p class="text-sm text-gray-600">Lost Time Incidents</p>
                        <p class="text-3xl font-bold text-blue-600"><?= $report['lost_time_incidents'] ?? 0 ?></p>
                    </div>

                    <div class="border-l-4 border-green-500 pl-4">
                        <p class="text-sm text-gray-600">Audits Conducted</p>
                        <p class="text-3xl font-bold text-green-600"><?= $report['safety_audits_conducted'] ?? 0 ?></p>
                    </div>

                    <div class="border-l-4 border-purple-500 pl-4">
                        <p class="text-sm text-gray-600">Training Sessions</p>
                        <p class="text-3xl font-bold text-purple-600"><?= $report['training_sessions_held'] ?? 0 ?></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?= $this->endSection() ?>
