<?php
namespace App\Libraries;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class ExcelExport
{
    protected $data;

    public function __construct($data)
    {
        $this->data = $data;
    }

    public function export()
    {
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();

        // Add column titles as the first row
        $column = 'A';
        foreach ($this->data[0] as $field => $value) {
            $sheet->setCellValue($column . '1', $field);
            $column++;
        }

        // Add data to the sheet
        $row = 2;
        foreach ($this->data as $record) {
            $column = 'A';
            foreach ($record as $value) {
                $sheet->setCellValue($column . $row, $value);
                $column++;
            }
            $row++;
        }

        // Create a writer and get the file content
        $writer = new Xlsx($spreadsheet);
        ob_start();
        $writer->save('php://output');
        $fileContent = ob_get_clean();

        return $fileContent;
    }
#This code is generated by Tingala CRUD generator

}
    
    